### ISSUE TITLE
Running FragGeneScan directly w/o their perl wrapper?

### ISSUE THREAD

**Issue by mr-c** [ProteinsWebTeam/ebi-metagenomics-cwl#2]
I see that FragGeneScan is run directly:

https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/workflows/command_line_tools/FragGeneScan1_20.cwl#L14

without the `run_FragGeneScan.pl` wrapper that they distributed.

Is this on purpose?

**Comment by mscheremetjew** [comment]
Yes, this was done on purpose. As you said it is just a Perl wrapper around a C binary.
