### ISSUE TITLE
post-mapSeq processing

### ISSUE THREAD

**Issue by mr-c** [ProteinsWebTeam/ebi-metagenomics-cwl#27]
- [x] for reads based pipeline
- [x] for assembly based pipeline

**Comment by rdfinn** [comment]
Both the same, sent you commands yesterday on slack.

/hps/nobackup/production/metagenomics/CWL/rdf/code/mgportal/analysis-pipeline/perl/mapseq2biom.pl --otuTable consensus_taxonomy_7_levels.otu --query  ERZ376968_infernal_SSU.mapseq --outFile ERZ376968_infernal_SSU.tsv  --label ERZ376968 --krona ERZ376968_SSU.txt

/hps/nobackup/production/metagenomics/production-scripts/current/mgportal/analysis-pipeline/python/tools/KronaTools-2.3/bin/ktImportText ERZ376968_SSU.txt -o ERZ376968_SSU.html

biom convert -i ERZ376968_infernal_SSU.tsv -o ERZ376968_infernal_SSU.biom --to-hdf5 --table-type="OTU table"

biom convert -i ERZ376968_infernal_SSU.tsv -o ERZ376968_infernal_SSU.json --to-json --table-type="OTU table"

**Comment by rdfinn** [comment]
Currently, we are using the biom installed within QIIME, however we will install on its own from here:http://biom-format.org/

You should point the CWL at this as being the source.

The Krona tool is a little fiddly to get going, you need to set the PERL5LIB.  However, the existing v3.0 pipeline config should have this already set. Let me know if there are issues.

**Comment by mr-c** [comment]
Done in https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/pull/39
