### ISSUE TITLE
reference database for mapseq

### ISSUE THREAD

**Issue by mr-c** [ProteinsWebTeam/ebi-metagenomics-cwl#31]

**Comment by rdfinn** [comment]
These have been generated and placed in the central CWL data directory:
/hps/nobackup/production/metagenomics/CWL/data/libraries/SILVA

Within there, we have
 99_otus.fasta - The reference database
consensus_taxonomy_7_levels.txt  - this is the taxonomy for the reference database.
99_otus.fasta.mscluster - If not present, MAPseq will generate this file....we do not want this re-generated for each run.
consensus_taxonomy_7_levels.otu  - this is required by me lovely perl scripts.

**Comment by mr-c** [comment]
Fixed in 	6c2aa47
Thanks!
