### ISSUE TITLE
Test if toil can deal with dynamic memory requests

### ISSUE THREAD

**Issue by rdfinn** [ProteinsWebTeam/ebi-metagenomics-cwl#73]
Running on some large datasets, the job was killed due to memory usage (esl-sfetch-index.cwl).  I have changed this in my local version, but it does not make sense to request so much for most jobs.

**Comment by mr-c** [comment]
This is known not to work :-( https://github.com/BD2KGenomics/toil/issues/1647

**Comment by mr-c** [comment]
This has been fixed in recent Toil releases and verified by me
